with 

source as (

    select * from {{ source('contemporani', 'admProductos') }}

),

renamed as (

    select
        cidproducto,
        ccodigoproducto,
        cnombreproducto,
        ctipoproducto,
        ccontrolexistencia,
        cstatusproducto,
        cidvalorclasificacion1,
        cidvalorclasificacion2,
        cidvalorclasificacion3,
        cidvalorclasificacion4,
        cidvalorclasificacion5,
        cidvalorclasificacion6,
        cprecio1
        -- cfechaaltaproducto,
        -- cidfotoproducto,
        -- cdescripcionproducto,
        -- cmetodocosteo,
        -- cpesoproducto,
        -- ccomventaexcepproducto,
        -- ccomcobroexcepproducto,
        -- ccostoestandar,
        -- cmargenutilidad,
        -- cidunidadbase,
        -- cidunidadnoconvertible,
        -- cfechabaja,
        -- cimpuesto1,
        -- cimpuesto2,
        -- cimpuesto3,
        -- cretencion1,
        -- cretencion2,
        -- cidpadrecaracteristica1,
        -- cidpadrecaracteristica2,
        -- cidpadrecaracteristica3,
        -- csegcontproducto1,
        -- csegcontproducto2,
        -- csegcontproducto3,
        -- ctextoextra1,
        -- ctextoextra2,
        -- ctextoextra3,
        -- cfechaextra,
        -- cimporteextra1,
        -- cimporteextra2,
        -- cimporteextra3,
        -- cimporteextra4,
        -- cprecio2,
        -- cprecio3,
        -- cprecio4,
        -- cprecio5,
        -- cprecio6,
        -- cprecio7,
        -- cprecio8,
        -- cprecio9,
        -- cprecio10,
        -- cbanunidades,
        -- cbancaracteristicas,
        -- cbanmetodocosteo,
        -- cbanmaxmin,
        -- cbanprecio,
        -- cbanimpuesto,
        -- cbancodigobarra,
        -- cbancomponente,
        -- ctimestamp,
        -- cerrorcosto,
        -- cfechaerrorcosto,
        -- cpreciocalculado,
        -- cestadoprecio,
        -- cbanubicacion,
        -- cesexento,
        -- cexistencianegativa,
        -- ccostoext1,
        -- ccostoext2,
        -- ccostoext3,
        -- ccostoext4,
        -- ccostoext5,
        -- cfeccosex1,
        -- cfeccosex2,
        -- cfeccosex3,
        -- cfeccosex4,
        -- cfeccosex5,
        -- cmoncosex1,
        -- cmoncosex2,
        -- cmoncosex3,
        -- cmoncosex4,
        -- cmoncosex5,
        -- cbancosex,
        -- cescuotai2,
        -- cescuotai3,
        -- cidunidadcompra,
        -- cidunidadventa,
        -- csubtipo,
        -- ccodaltern,
        -- cnomaltern,
        -- cdesccorta,
        -- cidmoneda,
        -- cusabascu,
        -- ctipopaque,
        -- cprecselec,
        -- cdesglosai2,
        -- csegcontproducto4,
        -- csegcontproducto5,
        -- csegcontproducto6,
        -- csegcontproducto7,
        -- cnomodcomp,
        -- cctapred,
        -- cnodescomp,
        -- cidunixml,
        -- cclavesat,
        -- ccantidadfiscal

    from source

)

select * from renamed
