with 

source as (

    select * from {{ source('contemporani', 'admDocumentos') }}

),

renamed as (

    select
        ciddocumento,
        ciddocumentode,
        cidconceptodocumento,
        cseriedocumento,

        date(timestamp(datetime(timestamp(cfecha), "America/Mexico_City"))) as cfecha,
        
        crazonsocial,
        cidmoneda,
        ctipocambio,
        cgasto1,
        cgasto2,
        cgasto3,
        ctotalunidades,
        cneto,
        ccancelado
        
        -- cfolio,
        -- cidclienteproveedor,
        -- crfc,
        -- cidagente,
        -- cfechavencimiento,
        -- cfechaprontopago,
        -- cfechaentregarecepcion,
        -- cfechaultimointeres,
        -- creferencia,
        -- cobservaciones,
        -- cnaturaleza,
        -- ciddocumentoorigen,
        -- cplantilla,
        -- cusacliente,
        -- cusaproveedor,
        -- cafectado,
        -- cimpreso,
        -- cdevuelto,
        -- cidprepoliza,
        -- cidprepolizacancelacion,
        -- cestadocontable,
        -- cimpuesto1,
        -- cimpuesto2,
        -- cimpuesto3,
        -- cretencion1,
        -- cretencion2,
        -- cdescuentomov,
        -- cdescuentodoc1,
        -- cdescuentodoc2,
        -- ctotal,
        -- cpendiente,
        -- cdescuentoprontopago,
        -- cporcentajeimpuesto1,
        -- cporcentajeimpuesto2,
        -- cporcentajeimpuesto3,
        -- cporcentajeretencion1,
        -- cporcentajeretencion2,
        -- cporcentajeinteres,
        -- ctextoextra1,
        -- ctextoextra2,
        -- ctextoextra3,
        -- cfechaextra,
        -- cimporteextra1,
        -- cimporteextra2,
        -- cimporteextra3,
        -- cimporteextra4,
        -- cdestinatario,
        -- cnumeroguia,
        -- cmensajeria,
        -- ccuentamensajeria,
        -- cnumerocajas,
        -- cpeso,
        -- cbanobservaciones,
        -- cbandatosenvio,
        -- cbancondicionescredito,
        -- cbangastos,
        -- cunidadespendientes,
        -- ctimestamp,
        -- cimpcheqpaq,
        -- csistorig,
        -- cidmonedca,
        -- ctipocamca,
        -- cescfd,
        -- ctienecfd,
        -- clugarexpe,
        -- cmetodopag,
        -- cnumparcia,
        -- ccantparci,
        -- ccondipago,
        -- cnumctapag,
        -- cidproyecto,
        -- cidcuenta,
        -- cguiddocumento,
        -- cusuario,
        -- ctransactionid,
        -- cidcopiade,
        -- cveresque

    from source

)

select * from renamed
